"""Eliminar columnas size_in_kb, feature_count y product_count

Revision ID: 7473c406f67e
Revises: 598ffa33502d
Create Date: 2024-11-20 12:09:11.957663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7473c406f67e'
down_revision = '598ffa33502d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('size_in_kb')

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.drop_column('feature_count')
        batch_op.drop_column('product_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_count', mysql.INTEGER(display_width=11), autoincrement=False, 
                                      nullable=False))
        batch_op.add_column(sa.Column('feature_count', mysql.INTEGER(display_width=11), autoincrement=False, 
                                      nullable=False))

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_in_kb', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
