"""Añadir columnas físicas feature_count, product_count y size_in_kb

Revision ID: dda763e701cd
Revises: 7473c406f67e
Create Date: 2024-11-20 12:22:26.470971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda763e701cd'
down_revision = '7473c406f67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_in_kb', sa.Float(), nullable=False))

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.drop_column('product_count')
        batch_op.drop_column('feature_count')

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('size_in_kb')

    # ### end Alembic commands ###
