name: Commits Syntax Checker

on:
  pull_request:
    branches: [main, develop]  # Permitir PR hacia main y develop
    types: [opened, reopened, edited, review_requested, synchronize]
  push:
    branches:
      - "main"
      - "develop"  # Ejecutar también en pushes hacia develop
  workflow_call:  # Dejarlo para ser invocado desde otros workflows si es necesario
    inputs:
      test_branch:
        description: "The branch to test"
        required: true

jobs:
  check:
    name: Validate Commit Messages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # SHA anclado para actions/checkout v3

      # Validate Commit Messages
      - name: Validate Commit Messages
        uses: wagoid/commitlint-github-action@v4  # Usar la última versión estable de wagoid
        with:
          configFile: commitlint.config.js

      # Verify Message Rules
      - name: Verify Message Rules
        run: |
          npx commitlint --edit $(git log -1 --pretty=%B)
        env:
          CONVENTIONAL_COMMITS_RULES: |
            {
              "type-enum": ["feat", "fix", "docs", "style", "test"],
              "subject-case": ["sentence-case"],
              "subject-empty": [false],
              "subject-full-stop": [false],
              "header-max-length": [50],
              "body-max-line-length": [72],
              "footer-max-line-length": [72]
            }
