name: Selenium Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  selenium:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

      - name: Check Chrome Installation
        run: google-chrome --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Application
        run: |
          FLASK_ENV=testing flask run --host=0.0.0.0 --port=5000 &
        env:
          FLASK_APP: app
          FLASK_ENV: testing
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_TEST_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password

      - name: Wait for Flask to be ready
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:5000 | grep -q "expected_keyword_or_response"; then
              echo "Flask application is ready."
              break
            fi
            echo "Waiting for Flask to be ready..."
            sleep 5
          done

      - name: Wait for a specific element in Selenium
        run: |
          python - <<EOF
          from selenium import webdriver
          from selenium.webdriver.common.by import By
          from selenium.webdriver.support.ui import WebDriverWait
          from selenium.webdriver.support import expected_conditions as EC
          from selenium.webdriver.chrome.service import Service
          from selenium.webdriver.chrome.options import Options
          from webdriver_manager.chrome import ChromeDriverManager

          # Configurar Chrome para Selenium
          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")
          service = Service(ChromeDriverManager().install())
          driver = webdriver.Chrome(service=service, options=options)

          try:
              driver.get("http://localhost:5000")
              WebDriverWait(driver, 20).until(
                  EC.presence_of_element_located((By.XPATH, "//h1[contains(@class, 'h2 mb-3') and contains(., 'Latest datasets')]"))
              )
              print("Elemento encontrado en Selenium.")
          except Exception as e:
              print(f"Error al encontrar el elemento: {e}")
              driver.save_screenshot("selenium_error.png")
              raise
          finally:
              driver.quit()
          EOF

      - name: Run Selenium Tests
        env:
          SELENIUM_HOST: localhost
          SELENIUM_PORT: 4444
        run: |
          pytest app/modules/ --maxfail=3 --disable-warnings
