name: Selenium Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  selenium:
    name: Run Selenium Tests
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2048m

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask Application
        run: |
          FLASK_ENV=testing flask run --host=0.0.0.0 --port=5000 &
        env:
          FLASK_APP: app
          FLASK_ENV: testing
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_TEST_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password

      - name: Wait for Flask to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000 | grep -q "expected_keyword_or_response"; then
              echo "Flask application is ready."
              break
            fi
            echo "Waiting for Flask to be ready..."
            sleep 5
          done

      - name: Run Selenium Tests
        env:
          SELENIUM_HOST: localhost
          SELENIUM_PORT: 4444
        run: |
          pytest app/modules/ --maxfail=3 --disable-warnings
